package citizenmanagementplatform;

public enum Menu {
    MAIN_PAGE, JUSTICE_MINISTRY, JUSTICE_MINISTRY_PROCEDURES, OBTAIN_CRIMINAL_REPORT_CERTIFICATE,
    AUTHENTICATE_CLAVE_PIN, AUTHENTICATE_CLAVE_PIN_CHECK, OBTAIN_CRIMINAL_REPORT_CERTIFICATE_IN_PROCESS,
    SHOW_AMOUNT_TO_PAY, CARD_DATA_FORM, CERTIFICATE_OPTIONS, PDF_VIEWER
}
